### ISSUE TITLE
Favorited Games Not Highlighted in GBOnion Multicolor Theme

### ISSUE THREAD

**Issue by vinsh3nt** [mugwomp93/GarlicOS_Customization#1]
Minor issue but it's difficult to tell which games have been favorited or not with this theme. I haven't checked for the other themes.

**Comment by mugwomp93** [comment]
I've updated "color-favorite-inactive" in settings.json for GBMini_for_Garlic, GBOnion_for_Garlic, and GBOnion_Multicolor to highlight favorited games in the console lists. If you don't want to download the zip again, you can change the color specified for "color-favorite-inactive" in the settings.json file in the skin folder from "#686868" to "#57bbe9" (or another color if you prefer).
